### PR TITLE
Update Readme and add v1

### PR DESCRIPTION
**Pull request by fr-ser**
**What this PR does / why we need it**:
There was some stuff missing from the README (e.g. hosts value for ingress) and the commands are not executable (incubator as chart repo name, even though the example uses owkin and a typo in pypiserver)
I also added the add repo part to the readme, even though on https://hub.helm.sh/charts/owkin/pypiserver it can be found in the right widget

**Special notes for your reviewer**:
The autoformatter also did some magic :wink: 
In the yaml I only added an entry, but the line indentation was adjusted, which is why the whole file "appears" changed

**Checklist**:
- [x] Bumped chart version in Chart.yaml

### CODE REVIEW

**Comment by fr-ser** [comment]
@ClementGautier, @camillemarini  I am not clear on the CI/Travis process here... Maybe the index.yaml is build automatically...

Also it more important for all those changes here to be in the branch gh-pages than master, but I guess you guys "start" from master

**Comment by ClementGautier** [comment]
Hello @fr-ser and thanks a lot for the contrib!

I'll have a look at the CI process tomorrow (travis shouldn't have commited the files here, only on the gh-pages branch as you guessed it) but the code looks good :)

**Comment by fr-ser** [comment]
Feel free too close this PR and apply these changes yourself.

Besides the changes in the Readme the (maybe more important) change is only the release of version 1. Without this, the explicit version has to always be included in the helm install command.

**Comment by ClementGautier** [comment]
Ok I see, this branch started from gh-pages, that's why you also fetched the travis commit. I'm closing this one in favor of #5 that I'm going to merge right away.

Thanks again for the contribution

**Pull request closed without merging**
